FROM  streamsets/datacollector


ADD ./sdc-data/streamsets-datacollector-apache-kafka_0_10-lib/* $SDC_HOME/streamsets-libs/streamsets-datacollector-apache-kafka_0_10-lib/lib
#RUN ls /$SDC_HOME/streamsets-libs/streamsets-datacollector-apache-kafka_0_10-lib/lib -l
#RUN cp -R  /data/streamsets-datacollector-apache-kafka_0_10-lib/  $SDC_HOME/streamsets-libs/streamsets-datacollector-apache-kafka_0_10-lib/lib
